name: Code Review Workflow

on:
  push:
    branches:
      - main

jobs:
  code_review:
    runs-on: ubuntu-latest

    container:
      image: node:20  # Use a Node.js Docker image with Node.js version >=20

    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Install Dependencies
        run: npm install

      - name: Lint Code
        run: npm run lint
        continue-on-error: true 

      - name: Analyze Code Quality
        run: npm run analyze 

      - name: Perform Security Scan
        run: npm run security-scan
