name: Code Review Workflow

on:
  push:
    branches:
      - main

jobs:
  review:
    runs-on: windows-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      
      - name: Install Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '12.x'
      
      - name: Install ESLint
        run: npm install eslint --save-dev

      - name: Install dependencies
        run: npm install
      
      - name: Run code analysis
        run: npm run analyze-code
      
      - name: Perform security scan
        run: npm run security-scan
