name: Dependency Updates

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  dependabot:
    runs-on: windows-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      # Setup Dependabot action
      - name: Dependabot
        uses: dependabot/dependabot-core@v0.131.0
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}   # Use the newly created secret here
          directory: '/'

      # Run tests if needed
      - name: Setup Node.js and Install Dependencies
        uses: actions/setup-node@v2
        with:
          node-version: '12.x'
      - run: npm ci
      - run: npm test
