name: Netlify Deployment

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '12.x'

      - name: Install Netlify CLI
        run: npm install -g netlify-cli
        continue-on-error: true 

      - name: Build
        run: npm run build

      - name: Deploy to Netlify
        run: netlify deploy --prod --auth ${{ secrets.GITHUB_TOKEN }}