name: Deployment Pipeline

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: windows-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '12.x'

      - name: Install dependencies
        run: npm install

      - name: Build 
        run: npm start  

      - name: Test
        run: npm test  # Update with your test command
        continue-on-error: true

      - name: Deploy to Netlify
        uses: nwtgck/actions-netlify@v1
        with:
          publish-dir: './public'  # Specify the directory to deploy
          deploy-dir: './dist'     # Specify the directory to deploy (optional)
          deploy-message: 'Deployed using GitHub Actions'  # Specify deployment message
          github-token: ${{ secrets.GITHUB_TOKEN }}  # Set Netlify authentication token as a secret
          enable-pull-request-comment: 'false'  # Disable PR comments (optional)