name: Documentation Deployment

on:
  push:
    branches:
      - main

jobs:
  build_and_deploy_docs:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install dependencies
        run: npm install

      - name: Build documentation
        run: npm run build-docs

      - name: Deploy documentation
        run: |
          git config --global user.email "actions@github.com"
          git config --global user.name "GitHub Actions"
          git checkout --orphan gh-pages
          git --no-pager add --all
          git --no-pager commit --message "GitHub Actions - Deploy documentation"
          git push origin gh-pages --force
