name: Scheduled Tasks

on:
    push:
        branches:
          - main
    

jobs:
  npm-install:
    runs-on: windows-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '12.x'  

      - name: Install dependencies
        run: npm install
